"use client";

// 폴더 보기 본문. view = 소스|테스트 2-pane(구분선 드래그로 비율 조절), edit = 테스트 Before|After DiffEditor.
// Monaco 는 SSR 에서 깨져 dynamic({ ssr:false }) (AGENTS.md).

import { useEffect, useRef, useState, useTransition, type ReactNode } from "react";
import dynamic from "next/dynamic";
import Link from "next/link";
import { usePathname } from "next/navigation";
import {
  Copy,
  Download,
  Loader2,
  Maximize2,
  Minimize2,
  Pencil,
  Play,
  RotateCcw,
  Sparkles,
} from "lucide-react";
import { generateFolderTest } from "@/app/project/[projectRef]/folder/actions";
import { iconForFile } from "@/components/file-icons";
import { RunPanel, useLiveRun } from "@/components/run-terminal";
import { Button, buttonVariants } from "@/components/ui/button";
import { MONACO_THEME as THEME, setupMonaco } from "@/lib/monaco-theme";
import { pushRecent } from "@/lib/recent-files";
import { cn } from "@/lib/utils";

type FileContent = { source: string; test: string | null; testDraft: string | null };

const Fallback = () => (
  <div className="flex h-full items-center justify-center bg-black">
    <Loader2 className="text-muted-foreground size-5 animate-spin" />
  </div>
);

const Editor = dynamic(() => import("@monaco-editor/react").then((m) => m.Editor), {
  ssr: false,
  loading: Fallback,
});
const DiffEditor = dynamic(() => import("@monaco-editor/react").then((m) => m.DiffEditor), {
  ssr: false,
  loading: Fallback,
});

const OPTIONS = {
  readOnly: true,
  minimap: { enabled: false },
  fontSize: 13,
  scrollBeyondLastLine: false,
  automaticLayout: true,
  padding: { top: 12 },
} as const;

function langOf(path: string): string {
  const ext = path.split(".").pop();
  if (ext === "ts" || ext === "tsx") return "typescript";
  if (ext === "js" || ext === "jsx" || ext === "mjs" || ext === "cjs") return "javascript";
  return "plaintext";
}

/** 테스트 파일이 아직 없을 때 표시용 이름. `src/lib/format.ts` → `format.test.ts` */
function guessTestName(path: string): string {
  const base = path.split("/").pop() ?? path;
  const dot = base.lastIndexOf(".");
  return dot === -1 ? `${base}.test` : `${base.slice(0, dot)}.test${base.slice(dot)}`;
}

function CodePane({ lang, value }: { lang: string; value: string }) {
  return (
    <Editor
      language={lang}
      theme={THEME}
      beforeMount={setupMonaco}
      loading={<Fallback />}
      value={value}
      options={OPTIONS}
    />
  );
}

function FileActions({
  text,
  filename,
  trailing,
}: {
  text: string;
  filename: string;
  trailing?: ReactNode;
}) {
  const copy = () => void navigator.clipboard.writeText(text).catch(() => {});
  const download = () => {
    const url = URL.createObjectURL(new Blob([text], { type: "text/plain" }));
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };
  return (
    <div className="ml-auto flex items-center gap-0.5">
      <Button
        size="icon-sm"
        variant="ghost"
        onClick={download}
        title="Download"
        aria-label="Download"
      >
        <Download />
      </Button>
      <Button size="icon-sm" variant="ghost" onClick={copy} title="Copy all" aria-label="Copy all">
        <Copy />
      </Button>
      {trailing}
    </div>
  );
}

function ReadOnlyBadge() {
  return (
    <span className="bg-muted text-muted-foreground shrink-0 rounded px-1 py-0.5 text-[10px]">
      Read-only
    </span>
  );
}

function DraftBadge({ version }: { version: number }) {
  return (
    <span
      title="Generated by AI and saved in Dante. Not committed to the repository."
      className="bg-brand-orange/10 text-brand-orange shrink-0 rounded px-1 py-0.5 text-[10px]"
    >
      AI draft · v{version}
    </span>
  );
}

const GENERATE_ERROR: Record<"budget" | "not-found" | "error" | "failed", string> = {
  budget: "You've exceeded this month's AI budget, so tests can't be generated.",
  "not-found": "Couldn't read this file from the repository. Refresh and try again.",
  error: "Test generation failed. Please try again in a moment.",
  failed: "Couldn't run test generation. Please try again in a moment.",
};

/** 테스트가 없을 때의 빈 칸. 생성·저장이 끝나면 액션이 refresh() 해 페이지가 draft 를 읽어 온다. */
function GenerateTest({ projectRef, file }: { projectRef: string; file: string }) {
  const [pending, startTransition] = useTransition();
  const [error, setError] = useState<keyof typeof GENERATE_ERROR | null>(null);

  const generate = () =>
    startTransition(async () => {
      setError(null);
      try {
        const result = await generateFolderTest(projectRef, file);
        if (!result.ok) setError(result.reason);
      } catch {
        setError("failed");
      }
    });

  return (
    <div className="text-muted-foreground flex h-full flex-col items-center justify-center gap-3 p-6 text-center">
      {pending ? (
        <p className="flex items-center gap-2 text-sm">
          <Loader2 className="size-4 animate-spin" />
          Generating test code.
        </p>
      ) : (
        <p className="text-sm">No tests yet.</p>
      )}
      <Button size="sm" onClick={generate} disabled={pending}>
        <Sparkles data-icon="inline-start" />
        Generate tests
      </Button>
      {error && (
        <p role="alert" className="text-destructive text-xs">
          {GENERATE_ERROR[error]}
        </p>
      )}
    </div>
  );
}

function Cell({
  className,
  show = true,
  children,
}: {
  className?: string;
  show?: boolean;
  children: ReactNode;
}) {
  if (!show) return null;
  return <div className={cn("border-border min-w-0", className)}>{children}</div>;
}

/** 본문 높이. 헤더 47px 만 빼면 화면 끝까지. */
const PANE_HEIGHT = "h-[calc(100svh-47px)]";
const GRID =
  "border-border relative grid grid-cols-2 grid-rows-[2.25rem_2.25rem_minmax(0,1fr)] overflow-hidden";

/** 터미널을 펼쳤을 때 높이(px). 끌어서 바꾸되 이 범위 안에서만. 최대는 본문의 70%. */
const TERMINAL_DEFAULT = 320;
const TERMINAL_MIN = 120;

function FileHeading({ name }: { name: string }) {
  return (
    <span className="flex min-w-0 items-center gap-1.5">
      {iconForFile(name.split("/").pop() ?? name, { className: "size-3.5 shrink-0" })}
      <span className="truncate font-mono font-semibold">{name}</span>
    </span>
  );
}

function ExpandButton({ active, onToggle }: { active: boolean; onToggle: () => void }) {
  return (
    <Button
      size="icon-sm"
      variant="ghost"
      onClick={onToggle}
      title={active ? "Restore" : "Expand"}
      aria-label={active ? "Restore" : "Expand"}
    >
      {active ? <Minimize2 /> : <Maximize2 />}
    </Button>
  );
}

function DragDivider({
  pct,
  onDown,
  onMove,
}: {
  pct: number;
  onDown: (e: React.PointerEvent<HTMLDivElement>) => void;
  onMove: (e: React.PointerEvent<HTMLDivElement>) => void;
}) {
  return (
    <div
      role="separator"
      aria-orientation="vertical"
      onPointerDown={onDown}
      onPointerMove={onMove}
      style={{ left: `${pct}%` }}
      className="group absolute inset-y-0 z-10 flex w-2 -translate-x-1/2 cursor-col-resize touch-none justify-center"
    >
      <span className="group-hover:bg-brand-orange/70 h-full w-0.5 rounded-full bg-transparent transition-colors" />
    </div>
  );
}

export function FileView({
  file,
  mode,
  projectRef,
  testPath,
  draftVersion = null,
  versionId = null,
  terminal = false,
  content,
}: {
  file: string;
  mode: "view" | "edit";
  projectRef: string;
  testPath: string | null;
  /** Test Code 가 레포 파일이 아니라 저장된 AI 생성 버전이면 그 번호. */
  draftVersion?: number | null;
  /** Test Code 칸에 보이는 저장된 버전의 id. 있으면 Run 으로 돌릴 수 있다. */
  versionId?: string | null;
  /** 하단 실행 터미널 바를 붙일지. 폴더 보기만 켠다(PR 화면은 실행이 없다). */
  terminal?: boolean;
  content: FileContent;
}) {
  const pathname = usePathname();
  const lang = langOf(file);
  const viewHref = `${pathname}?file=${encodeURIComponent(file)}`;
  const editHref = `${viewHref}&mode=edit`;
  const testName = testPath?.split("/").pop() ?? guessTestName(file);

  useEffect(() => {
    pushRecent(projectRef, file);
  }, [projectRef, file]);

  const gridRef = useRef<HTMLDivElement>(null);
  const [leftPct, setLeftPct] = useState(50);
  const onDividerDown = (e: React.PointerEvent<HTMLDivElement>) => {
    e.preventDefault();
    e.currentTarget.setPointerCapture(e.pointerId);
  };
  const onDividerMove = (e: React.PointerEvent<HTMLDivElement>) => {
    if (e.buttons !== 1 || !gridRef.current) return;
    const r = gridRef.current.getBoundingClientRect();
    setLeftPct(Math.min(80, Math.max(20, ((e.clientX - r.left) / r.width) * 100)));
  };

  // 실행 상태는 파일마다 따로다(부모가 key={file} 로 새로 띄운다). 파일을 옮기면 실행도 멈춘다.
  const run = useLiveRun(projectRef);
  // 하단 터미널. 접혀 있어도 바는 보인다. Run 을 누르면 펼친다.
  const shellRef = useRef<HTMLDivElement>(null);
  const [terminalOpen, setTerminalOpen] = useState(false);
  const [terminalHeight, setTerminalHeight] = useState(TERMINAL_DEFAULT);
  const onTerminalResizeDown = (e: React.PointerEvent<HTMLDivElement>) => {
    e.preventDefault();
    e.currentTarget.setPointerCapture(e.pointerId);
  };
  const onTerminalResizeMove = (e: React.PointerEvent<HTMLDivElement>) => {
    if (e.buttons !== 1 || !shellRef.current) return;
    const r = shellRef.current.getBoundingClientRect();
    setTerminalHeight(Math.min(r.height * 0.7, Math.max(TERMINAL_MIN, r.bottom - e.clientY)));
  };

  const [expanded, setExpanded] = useState<null | "left" | "right">(null);
  const toggle = (s: "left" | "right") => setExpanded((e) => (e === s ? null : s));
  const showLeft = expanded !== "right";
  const showRight = expanded !== "left";
  const expandedCols = expanded ? "minmax(0,1fr)" : undefined;

  if (mode === "edit") {
    const original = content.test ?? "";
    const draft = content.testDraft ?? original;

    return (
      <div className={cn(GRID, PANE_HEIGHT)} style={{ gridTemplateColumns: expandedCols }}>
        <Cell show={showLeft} className="bg-sidebar flex items-center border-b px-2.5 text-xs">
          <span className="font-semibold">Before</span>
        </Cell>
        <Cell show={showRight} className="bg-sidebar flex items-center border-b px-2.5 text-xs">
          <span className="font-semibold">After</span>
          <div className="ml-auto flex items-center gap-1">
            <Link href={viewHref} className={cn(buttonVariants({ variant: "ghost", size: "xs" }))}>
              Cancel
            </Link>
            {/* ponytail: 저장 동작은 다음 PR */}
            <Button variant="ghost" size="xs" disabled className="text-brand-orange">
              Save
            </Button>
            <span className="bg-border mx-0.5 h-4 w-px" />
            {/* ponytail: 되돌리기(After→원본) 다음 PR */}
            <Button size="icon-sm" variant="ghost" disabled title="Revert" aria-label="Revert">
              <RotateCcw />
            </Button>
          </div>
        </Cell>

        <Cell
          show={showLeft}
          className="bg-sidebar flex items-center gap-2.5 border-b px-2.5 text-xs"
        >
          <FileHeading name={testName} />
          <ReadOnlyBadge />
          <FileActions
            text={original}
            filename={testName}
            trailing={<ExpandButton active={expanded === "left"} onToggle={() => toggle("left")} />}
          />
        </Cell>
        <Cell
          show={showRight}
          className="bg-sidebar flex items-center gap-2.5 border-b px-2.5 text-xs"
        >
          <FileHeading name={testName} />
          <FileActions
            text={draft}
            filename={testName}
            trailing={
              <ExpandButton active={expanded === "right"} onToggle={() => toggle("right")} />
            }
          />
        </Cell>

        <div className={cn("min-h-0 bg-black", !expanded && "col-span-2")}>
          {expanded === "left" ? (
            <CodePane lang={lang} value={original} />
          ) : expanded === "right" ? (
            <Editor
              language={lang}
              theme={THEME}
              beforeMount={setupMonaco}
              loading={<Fallback />}
              value={draft}
              options={{ ...OPTIONS, readOnly: false }}
            />
          ) : (
            <DiffEditor
              language={lang}
              theme={THEME}
              beforeMount={setupMonaco}
              loading={<Fallback />}
              original={original}
              modified={draft}
              options={{
                ...OPTIONS,
                readOnly: false,
                originalEditable: false,
                renderSideBySide: true,
                renderSideBySideInlineBreakpoint: 0,
                useInlineViewWhenSpaceIsLimited: false,
                enableSplitViewResizing: false,
                overviewRulerBorder: false,
              }}
            />
          )}
        </div>
      </div>
    );
  }

  const cols = expanded ? "minmax(0,1fr)" : `minmax(0,${leftPct}fr) minmax(0,${100 - leftPct}fr)`;

  return (
    <div ref={shellRef} className={cn("flex flex-col", PANE_HEIGHT)}>
      <div
        ref={gridRef}
        className={cn(GRID, "min-h-0 flex-1")}
        style={{ gridTemplateColumns: cols }}
      >
        <Cell
          show={showLeft}
          className={cn(
            "bg-sidebar flex items-center border-b px-2.5 text-xs",
            showRight && "border-r"
          )}
        >
          <span className="font-semibold">Source Code</span>
        </Cell>
        <Cell
          show={showRight}
          className="bg-sidebar flex items-center gap-1.5 border-b px-2.5 text-xs"
        >
          <span className="font-semibold">Test Code</span>
          {content.test && (
            <div className="ml-auto flex items-center gap-0.5">
              {/* 실행은 저장된 버전(레포에서 가져온 것·AI draft 모두)을 돌린다. 한 번에 하나만. */}
              {versionId && (
                <Button
                  size="icon-sm"
                  variant="ghost"
                  onClick={() => {
                    setTerminalOpen(true);
                    void run.start(versionId);
                  }}
                  disabled={run.view?.running}
                  title={run.view?.running ? "Running…" : "Run tests"}
                  aria-label="Run tests"
                  className="text-brand-orange"
                >
                  {run.view?.running ? <Loader2 className="animate-spin" /> : <Play />}
                </Button>
              )}
              {/* draft 는 레포에 없는 파일이라 diff 기준(원본)이 없다 — 수정은 레포 테스트에만 */}
              {draftVersion === null && (
                <Link
                  href={editHref}
                  title="Edit"
                  aria-label="Edit"
                  className={cn(
                    buttonVariants({ variant: "ghost", size: "icon-sm" }),
                    "text-brand-orange hover:bg-brand-orange/10 hover:text-brand-orange"
                  )}
                >
                  <Pencil />
                </Link>
              )}
            </div>
          )}
        </Cell>

        <Cell
          show={showLeft}
          className={cn(
            "bg-sidebar flex items-center gap-2.5 border-b px-2.5 text-xs",
            showRight && "border-r"
          )}
        >
          <FileHeading name={file} />
          <ReadOnlyBadge />
          <FileActions
            text={content.source}
            filename={file.split("/").pop() ?? "source.txt"}
            trailing={<ExpandButton active={expanded === "left"} onToggle={() => toggle("left")} />}
          />
        </Cell>
        <Cell
          show={showRight}
          className="bg-sidebar flex items-center gap-2.5 border-b px-2.5 text-xs"
        >
          {content.test && (
            <>
              <FileHeading name={testName} />
              {draftVersion === null ? <ReadOnlyBadge /> : <DraftBadge version={draftVersion} />}
              <FileActions
                text={content.test}
                filename={testName}
                trailing={
                  <ExpandButton active={expanded === "right"} onToggle={() => toggle("right")} />
                }
              />
            </>
          )}
        </Cell>

        <Cell show={showLeft} className={cn("bg-black", showRight && "border-r")}>
          <CodePane lang={lang} value={content.source} />
        </Cell>
        <Cell show={showRight} className="bg-black">
          {content.test ? (
            <CodePane lang={lang} value={content.test} />
          ) : (
            <GenerateTest projectRef={projectRef} file={file} />
          )}
        </Cell>

        {!expanded && <DragDivider pct={leftPct} onDown={onDividerDown} onMove={onDividerMove} />}
      </div>
      {terminal && (
        <RunPanel
          view={run.view}
          open={terminalOpen}
          height={terminalHeight}
          onToggle={() => setTerminalOpen((open) => !open)}
          onResizeDown={onTerminalResizeDown}
          onResizeMove={onTerminalResizeMove}
        />
      )}
    </div>
  );
}
